import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";



const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify required weights
  // Optional: Use a CSS variable for manual control
  variable: "--font-raleway", 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={raleway.className}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
